name: Build simulator

on:
  push:
    branches:
      - '*'

jobs:
  run-binaries:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: prepare
        run: |
          sudo apt-get update &&
          sudo apt-get install g++-14 cmake make ninja-build python3 python3-dev git python3.12-venv apt-get install wget
